function(install_sharedLib_for_unittests)
    set(options OPTIONAL)
    set(oneValueArgs NAME LOCATION HEADER_NAME PACKAGE_NAME)
    set(multiValueArgs MULTI)

    cmake_parse_arguments(COPY_SHARED_LIB "${options}" "${oneValueArgs}"
                          "${multiValueArgs}" ${ARGN} )

    install(TARGETS ${COPY_SHARED_LIB_NAME}
        CONFIGURATIONS Release
        RUNTIME DESTINATION ${COPY_SHARED_LIB_PACKAGE_NAME}/bin/Release/${COPY_SHARED_LIB_LOCATION}
        LIBRARY DESTINATION ${COPY_SHARED_LIB_PACKAGE_NAME}/bin/Release/${COPY_SHARED_LIB_LOCATION}
        PUBLIC_HEADER DESTINATION ${COPY_SHARED_LIB_PACKAGE_NAME}/include/${COPY_SHARED_LIB_HEADER_NAME}
    )

    install(TARGETS ${COPY_SHARED_LIB_NAME}
        CONFIGURATIONS Debug
        RUNTIME DESTINATION ${COPY_SHARED_LIB_PACKAGE_NAME}/bin/Debug/${COPY_SHARED_LIB_LOCATION}
        LIBRARY DESTINATION ${COPY_SHARED_LIB_PACKAGE_NAME}/bin/Debug/${COPY_SHARED_LIB_LOCATION}
        PUBLIC_HEADER DESTINATION ${COPY_SHARED_LIB_PACKAGE_NAME}/include/${COPY_SHARED_LIB_HEADER_NAME}
    )

endfunction()
