function(install_target)

    set(options OPTIONAL)
    set(oneValueArgs NAMESPACE HEADER_NAME CMAKE_FILE EXPORT_NAME PACKAGE_NAME)
    set(multiValueArgs NAME)

    cmake_parse_arguments(INSTALL_TARGET "${options}" "${oneValueArgs}"
                          "${multiValueArgs}" ${ARGN} )

    install(TARGETS ${INSTALL_TARGET_NAME}
        EXPORT ${INSTALL_TARGET_EXPORT_NAME}_debug
        CONFIGURATIONS Debug
        ARCHIVE DESTINATION ${INSTALL_TARGET_PACKAGE_NAME}/lib/Debug
        LIBRARY DESTINATION ${INSTALL_TARGET_PACKAGE_NAME}/lib/Debug
        RUNTIME DESTINATION ${INSTALL_TARGET_PACKAGE_NAME}/bin/Debug
        PUBLIC_HEADER DESTINATION ${INSTALL_TARGET_PACKAGE_NAME}/include/${INSTALL_TARGET_HEADER_NAME}
    )

    install(TARGETS ${INSTALL_TARGET_NAME}
        EXPORT ${INSTALL_TARGET_EXPORT_NAME}_release
        CONFIGURATIONS Release
        ARCHIVE DESTINATION ${INSTALL_TARGET_PACKAGE_NAME}/lib/Release
        LIBRARY DESTINATION ${INSTALL_TARGET_PACKAGE_NAME}/lib/Release
        RUNTIME DESTINATION ${INSTALL_TARGET_PACKAGE_NAME}/bin/Release
        PUBLIC_HEADER DESTINATION ${INSTALL_TARGET_PACKAGE_NAME}/include/${INSTALL_TARGET_HEADER_NAME}
    )

    install(EXPORT ${INSTALL_TARGET_EXPORT_NAME}_debug
        DESTINATION ${INSTALL_TARGET_PACKAGE_NAME}/cmake/
        FILE ${INSTALL_TARGET_EXPORT_NAME}Config.cmake
        NAMESPACE ${INSTALL_TARGET_NAMESPACE}::
        CONFIGURATIONS DEBUG
    )

    install(EXPORT ${INSTALL_TARGET_EXPORT_NAME}_release
        DESTINATION ${INSTALL_TARGET_PACKAGE_NAME}/cmake/
        FILE ${INSTALL_TARGET_EXPORT_NAME}Config.cmake
        NAMESPACE ${INSTALL_TARGET_NAMESPACE}::
        CONFIGURATIONS RELEASE
    )
endfunction()